# Simple encoding - Pandas
***

## Imports

In [1]:
import pandas as pd              # pandas for handling mixed data sets

#### Create a sample data set

In [2]:
scratch_df = pd.DataFrame({'x1': ['A', 'A', 'A', 'A', 'A', 'B', 'B', 'B', 'B', 'B'],
                           'x2': ['C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L']})
scratch_df

  x1 x2
0  A  C
1  A  D
2  A  E
3  A  F
4  A  G
5  B  H
6  B  I
7  B  J
8  B  K
9  B  L

#### Encode categorical variables as binary dummies

In [5]:
pd.concat([scratch_df, pd.get_dummies(scratch_df)], axis=1)

,x1,x2,x1_A,x1_B,x2_C,x2_D,x2_E,x2_F,x2_G,x2_H,x2_I,x2_J,x2_K,x2_L
0,A,C,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,A,D,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,A,E,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,A,F,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
4,A,G,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
5,B,H,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
6,B,I,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
7,B,J,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
8,B,K,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
9,B,L,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0